service: moon-docs

provider:
  name: aws
  runtime: nodejs12.x
  stage: "dev"
  region: eu-central-1
  memorySize: 1024
  timeout: 20

functions:
  app:
    handler: serverless.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    package:
      exclude:
        - "*/*"
        - ".build/public/**"
      include:
        - ".build/**"
        - "node_modules/**"
        - "content/**"
